### ISSUE TITLE
Exception: decodeObjectForKey: class "NFFieldNotification" not loaded or does not exist

### ISSUE THREAD

**Issue by hskang9** [underwindfall/NFCAndroid#1]
Hello @underwindfall, I tried your android HCE and scanned it with Iphone Xs on iOS 12.1.2, and it shows this following error. This is also shown on Official CoreNFC app as well. Is this because the current android hce is not compatible with apple's specification? I am sure that they follow the specification from NFC forum.

```
2018-12-29 21:17:50.454300+0900 NFCTagReader[530:68425] [general] <NSXPCConnection: 0x283c24090> connection to service named com.apple.nfcd.service.corenfc: Exception caught during decoding of received message, dropping incoming message.
Exception: Exception while decoding argument 0 (#2 of invocation):
Exception: decodeObjectForKey: class "NFFieldNotification" not loaded or does not exist
2018-12-29 21:17:50.462534+0900 NFCTagReader[530:68425] [Assert] Cannot be called with asCopy = NO on non-main thread.
```

**Comment by underwindfall** [comment]
@hskang9 Hello there, have u ever tried using my [ios project](https://github.com/underwindfall/NFCReaderiOS) to scan the android HCE?

**Comment by underwindfall** [comment]
@hskang9 ahahaha i'm closing the issue

**Comment by ulian-onua** [comment]
@underwindfall I have the same issue when trying to read NFC using my iPhone 7 and Android Galaxy S7. I tested with both your apps.

Here a message that I got in logs:

2019-04-29 11:14:15.973070+0300 TagReader[4490:1146598] [general] <NSXPCConnection: 0x282e033c0> connection to service named com.apple.nfcd.service.corenfc: Exception caught during decoding of received message, dropping incoming message.
Exception: Exception while decoding argument 0 (#2 of invocation):
Exception: decodeObjectForKey: class "NFFieldNotification" not loaded or does not exist

Any ideas how this can be solved?

Thank you.

**Comment by underwindfall** [comment]
@ulian-onua base on what i have known, this is a problem about your ios account issue. You need to renew your developer account

**Comment by ulian-onua** [comment]
@underwindfall I don't have problems with my developer account. It is renewed and valid. Any other ideas? It is work in 100% cases on your test devices?

**Comment by underwindfall** [comment]
@ulian-onua I have been tested a lot of android devices , here is the list

- Samsung Galaxy S6
- Huawei P20
- Huawei P20 Pro
- Oneplus 5 plus
- Pixel 1
- Pixel 2

**Comment by ulian-onua** [comment]
@underwindfall ok. I tested your app not only with your iOS app but also with similar apps that read  that published on AppStore.
Unfortunately, I got the same behaviour.
I tested on two iOS devices: iPhone 7 and iPhone XS.
So I still think that the reason is in Android device.
I will try with other Android device and write here about the results.
Thanks.

**Comment by Screon** [comment]
@ulian-onua did you get any solution? I get the same problem...
