### ISSUE TITLE
nfcreadermessage not working consistently 

### ISSUE THREAD

**Issue by Alcimovich-NOUBISSI** [underwindfall/NFCAndroid#4]
Great app.. But I encountered an issue while using the app.. the card emulator is working but the reader isn't very well. It's reading sometimes.

**Comment by underwindfall** [comment]
sorry for the delay. actually that depends on the device, since the `NFC chip in different phones have different effects` I'm not sure I can do a step further.

**Comment by underwindfall** [comment]
closed issue since I havn't recevied any more information about this
